name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * 1" # Every monday at 3 AM

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: |
          docker run -d --rm -p 10389:10389 -p 10636:10636 rroemhild/test-openldap
          go test ./...
        env:
            CSRF_KEY: 'some-32-byte-key'
            SESSION_KEY: 'some-32-byte-key'
            LDAP_HOST: 'localhost'
            LDAP_PORT: 10389
            LDAP_BIND_USERNAME: 'cn=admin,dc=planetexpress,dc=com'
            LDAP_BIND_PASSWORD: 'GoodNewsEveryone'
            LDAP_BASE_DN: 'dc=planetexpress,dc=com'
